"""Provide common functions and definitions for the codegen module."""
from aas_core_codegen.common import Stripped


WARNING = Stripped(
    f"""\
/*
 * This code has been automatically generated by aas_core3_0_sk_codegen.
 * Do NOT edit or append.
 */"""
)
